# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Personal_Projects\Daily_Task_Management_QtDesigner\main_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(685, 489)
        Form.setStyleSheet("background-color:rgb(198, 149, 94)")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 691, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 691, 61))
        self.label.setStyleSheet("background: rgb(255, 208, 133);\n"
"color: black;\n"
"font: 25pt \"Bodoni MT\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.saveButton = QtWidgets.QPushButton(self.tab_3)
        self.saveButton.setGeometry(QtCore.QRect(400, 390, 131, 23))
        self.saveButton.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.saveButton.setObjectName("saveButton")
        self.deleteTaskButton = QtWidgets.QPushButton(self.tab_3)
        self.deleteTaskButton.setGeometry(QtCore.QRect(540, 390, 101, 23))
        self.deleteTaskButton.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.tasksListWidget = QtWidgets.QListWidget(self.tab_3)
        self.tasksListWidget.setGeometry(QtCore.QRect(400, 130, 241, 251))
        self.tasksListWidget.setStyleSheet("background-color:rgb(255, 208, 133);\n"
"border-radius: 10px; \n"
"font: 12pt;")
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.showTodayButton = QtWidgets.QPushButton(self.tab_3)
        self.showTodayButton.setGeometry(QtCore.QRect(40, 100, 331, 23))
        self.showTodayButton.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.showTodayButton.setObjectName("showTodayButton")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 130, 331, 251))
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Bodoni MT\";\n"
"font-color: rgb(0, 0, 0)")
        self.calendarWidget.setObjectName("calendarWidget")
        self.addButton = QtWidgets.QPushButton(self.tab_3)
        self.addButton.setGeometry(QtCore.QRect(560, 100, 81, 23))
        self.addButton.setStyleSheet("background-color:rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.addButton.setObjectName("addButton")
        self.taskLineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.taskLineEdit.setGeometry(QtCore.QRect(400, 100, 151, 20))
        self.taskLineEdit.setStyleSheet("font: 12pt;\n"
"background-color:rgb(255, 208, 133);")
        self.taskLineEdit.setObjectName("taskLineEdit")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", " Daily Task Planner"))
        self.saveButton.setText(_translate("Form", "Save Changes"))
        self.deleteTaskButton.setText(_translate("Form", "Delete Task"))
        self.showTodayButton.setText(_translate("Form", "Show Today"))
        self.addButton.setText(_translate("Form", "Add New"))
        self.taskLineEdit.setPlaceholderText(_translate("Form", "Insert Text..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Task Planner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Tab 2"))
import res_rc
