# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Personal_Projects\Daily_Task_Management_QtDesigner\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(635, 440)
        Form.setStyleSheet("background-color:rgb(198, 149, 94)")
        self.tasksListWidget = QtWidgets.QListWidget(Form)
        self.tasksListWidget.setGeometry(QtCore.QRect(380, 130, 241, 251))
        self.tasksListWidget.setStyleSheet("background-color:rgb(255, 208, 133);\n"
"border-radius: 10px; \n"
"font: 12pt;")
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 641, 61))
        self.label.setStyleSheet("background: rgb(255, 208, 133);\n"
"color: black;\n"
"font: 25pt \"Bodoni MT\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 130, 331, 251))
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Bodoni MT\";\n"
"font-color: rgb(0, 0, 0)")
        self.calendarWidget.setObjectName("calendarWidget")
        self.addButton = QtWidgets.QPushButton(Form)
        self.addButton.setGeometry(QtCore.QRect(540, 100, 81, 23))
        self.addButton.setStyleSheet("background-color:rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.addButton.setObjectName("addButton")
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setGeometry(QtCore.QRect(380, 390, 131, 23))
        self.saveButton.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.saveButton.setObjectName("saveButton")
        self.taskLineEdit = QtWidgets.QLineEdit(Form)
        self.taskLineEdit.setGeometry(QtCore.QRect(380, 100, 151, 20))
        self.taskLineEdit.setStyleSheet("font: 12pt;\n"
"background-color:rgb(255, 208, 133);")
        self.taskLineEdit.setObjectName("taskLineEdit")
        self.deleteTaskButton = QtWidgets.QPushButton(Form)
        self.deleteTaskButton.setGeometry(QtCore.QRect(520, 390, 101, 23))
        self.deleteTaskButton.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.deleteTaskButton.setObjectName("deleteTaskButton")
        self.showTodayButton = QtWidgets.QPushButton(Form)
        self.showTodayButton.setGeometry(QtCore.QRect(20, 100, 331, 23))
        self.showTodayButton.setStyleSheet("background-color: rgb(255, 208, 133);\n"
"font: 8pt \"Open Sans\";\n"
"border-radius: 10px;")
        self.showTodayButton.setObjectName("showTodayButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 631, 20))
        self.label_2.setStyleSheet("font: 10pt;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", " Daily Task Planner"))
        self.addButton.setText(_translate("Form", "Add New"))
        self.saveButton.setText(_translate("Form", "Save Changes"))
        self.taskLineEdit.setPlaceholderText(_translate("Form", "Insert Text..."))
        self.deleteTaskButton.setText(_translate("Form", "Delete Task"))
        self.showTodayButton.setText(_translate("Form", "Show Today"))
        self.label_2.setText(_translate("Form", "Remember to Save Changes after you have checked/unchecked a task."))
import res_rc
